<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LocalThemeExtractor</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="MediaBrowser.Common" Version="4.8.0.24-beta" />
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.8.0.24-beta" />
  </ItemGroup>
</Project>
